---

- name: Update pacman.conf to include multilib
  become: yes
  blockinfile:
    path: /etc/pacman.conf
    block: |
      [multilib]
      Include = /etc/pacman.d/mirrorlist

- name: Arch Base
  become: yes
  pacman:
    name: base
    state: present

- name: Arch Base-Devel
  become: yes
  pacman:
    name: base-devel
    state: present

- name: Linux Firmware
  become: yes
  pacman:
    name: linux-firmware
    state: present

- name: Make sure yay is installed
  include_role:
    name: yay

- name: Install remaining base packages
  become: yes
  package: name={{item}} state=present
  with_items: "{{ pkgs }}"
  tags: [ 'pkgs' ]
