# To re-encrypt any sops-encrypted secrets files after changing keys in this file, use:
#   sops updatekeys secrets/host/filename.yaml
key_fingerprints:
  # Key fingerprints of administrators of the system.
  #
  # To add a new entry:
  #
  # 1. Create a directory to store your age keys: `mkdir -p ~/.config/sops/age`
  # 2. Generate an SSH key on your computer: `ssh-keygen -t ed25519 -f ~/.ssh/sops-ssh -N ""`
  #        Note: if you copy this key to another computer, ensure it has 0600 permissions.
  # 3. From the private SSH key, generate an age private key:
  #    ssh-to-age -private-key -i ~/.ssh/sops-ssh -o ~/.config/sops/age/keys.txt
  # 4. From the public SSH key, generate an age public key and place it in this config file
  #    as a new entry below:
  #    ssh-to-age -i ~/.ssh/sops-ssh.pub
  - &user_anoa age1rg0s0acla64mdd8kxts0cpfygn55yuqgw9f6hhu5ucljdla34e4svytm6v

  # Key fingerprints for hosts in my infrastructure.
  #
  # To add a new entry:
  #
  # 1. Generate a private age key: `age-keygen -o key.txt`
  # 2. Copy the private key to the host:
  #    * For live systems:
  #        USER=root \
  #        REMOTE_HOST=1.2.3.4 \
  #        PORT=22 \
  #        ssh -p$PORT $USER@$REMOTE_HOST 'mkdir -p /var/lib/sops-nix' \
  #            && scp -P$PORT key.txt $USER@$REMOTE_HOST:/var/lib/sops-nix/key.txt
  #    * For test VMs:
  #        USER=root \
  #        QEMU_NET_OPTS="hostfwd=tcp::2222-:22" \
  #        ssh $USER@localhost 'mkdir -p /var/lib/sops-nix' \
  #            && scp key.txt $USER@localhost:/var/lib/sops-nix/key.txt
  - &host_plonkie age1a3ex8puz5n39npcaf9avudcp57j20pmrxn3e46mwsyz3qegdzqqq8hldw6


# This section determines the keys that secrets under certain folder paths are encrypted for.
# (AKA which keys (key_groups) can decrypt which secrets (path_regex))
creation_rules:
  - path_regex: secrets/personal_common/[^/]+\.?(yaml|env|)$
    key_groups:
      # note: you MUST specify both `pgp` and `age` fields, even if one is empty.
      - pgp: []
        age:
        - *user_anoa
  - path_regex: secrets/plonkie/[^/]+\.?(yaml|env|)$
    key_groups:
      # note: you MUST specify both `pgp` and `age` fields, even if one is empty.
      - pgp: []
        age:
        - *user_anoa
        - *host_plonkie