{
  imports = [
    ./aliases.nix
    ./fonts.nix
    ./gtk.nix
    ./qt.nix
    ./kdeconnect.nix
    ./launchers.nix
    ./picom.nix
    ./dunst.nix
    ./element.nix
    ./terminal.nix
    ./gui.nix
    ./gnome.nix
    ./kde.nix
    ./applications.nix
    ./i3.nix
    ./plymouth.nix
    ./sway.nix
    ./steam.nix
    ./kanshi.nix
    ./thunderbird.nix
    ./tilewm.nix
    ./wofi-emoji.nix
    ./script.nix
    ./xterm-no-display.nix
  ];
}
