{
    imports = [
        ./android.nix
        ./antivirus.nix
        ./backup.nix
        ./software.nix
        ./disk.nix
        ./flatpak.nix
        ./git.nix
        ./kernel.nix
        ./neovim.nix
        ./network.nix
        ./nix.nix
        ./printing.nix
        ./syst.nix
        ./regional.nix
        ./security.nix
        ./shell.nix
        ./swap.nix
        ./systemd.nix
        ./tmp.nix
        ./virtualisation.nix
        ./vpn.nix
    ];
}
