---
pkgs:
  - network-manager-applet 
  - xdg-utils 
  - xdg-user-dirs 
  - lightdm 
  - xorg 
  - xorg-xrandr 
  - i3-gaps 
  - alacritty 
  - xterm 
  - rofi 
  - pavucontrol 
  - lightdm-gtk-greeter 
  - lightdm-gtk-greeter-settings 
  - firefox 
  - yubikey-manager 
  - yubikey-personalization 
  - picom 
  - ttf-font-awesome 
  - breeze-gtk 
  - discord 
  - gimp 
  - libreoffice-fresh 
  - lxappearance 
  - obs-studio 
  - vlc 
  - libfdk-aac 
  - libva-intel-driver 
  - scrot 
  - ttf-liberation 
  - zathura 
  - zathura-cb 
  - zathura-djvu 
  - zathura-pdf-mupdf 
  - zathura-ps 
  - feh 
  - noto-fonts
  - ttf-nerd-fonts-symbols 
  - deepin-screenshot

yaypkgs:
  - plymouth-git 
  - polybar 
  - joplin-appimage 
  - ttf-ms-fonts 
  - wps-office 
  - ttf-wps-fonts 
  - wps-office-fonts 
  - wps-office-mime 
  - arch-silence-grub-theme-git 
  - g810-led-git 
  - headsetcontrol