---
- name: Install remaining dev packages
  package: name={{item}} state=present
  with_items: "{{ pkgs }}"
  tags: [ 'pkgs' ]
  become: yes

- name: Make sure yay is installed
  include_role:
    name: yay

- name: Install remaining dev yay packages
  yay: name={{item}} user=wil
  with_items: "{{ yaypkgs }}"
  tags: [ 'pkgs' ]
  become: yes


- name: Install rust up
  package: name=rustup state=present
  tags: ['pkgs']
  become: yes

- name: Check if rust is installed
  stat: path=/home/wil/.rustup/toolchains/stable-x86_64-unknown-linux-gnu
  register: p
  
- name: Install rust
  shell: "rustup update stable"
  when: not p.stat.exists

- name: Update Rust
  command: rustup update
  changed_when: false

- name: Add user to docker group
  user:
    name: wil
    groups: docker
    append: yes

- name: Enable docker service
  become: yes
  systemd:
    enabled: yes
    name: docker.service